# Generated by Django 3.1.4 on 2020-12-17 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BBSORecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_details', models.CharField(blank=True, help_text='e.g. In the kitchen on the 4th floor.', max_length=50)),
                ('PTW', models.CharField(blank=True, max_length=10, verbose_name='Permit To Work Number')),
                ('JSA', models.CharField(blank=True, max_length=10, verbose_name='Job Safety Analysis Number')),
                ('details_of_observation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BBSORecordActions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_action', models.TextField(verbose_name='Recommended Action')),
                ('bbso_record_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='bbso.bbsorecords', verbose_name='BBSO Record')),
            ],
        ),
    ]
